package com.bouchardm.tp3.biblio.mapping;
// Generated 2013-12-16 12:24:15 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * BiCopiesarticles generated by hbm2java
 */
public class BiCopiesarticles  implements java.io.Serializable {


     private BiCopiesarticlesId id;
     private BiArticles biArticles;
     private BiEtatarticle biEtatarticle;
     private Set<BiEmprunts> biEmpruntses = new HashSet<BiEmprunts>(0);

    public BiCopiesarticles() {
    }

	
    public BiCopiesarticles(BiCopiesarticlesId id, BiArticles biArticles) {
        this.id = id;
        this.biArticles = biArticles;
    }
    public BiCopiesarticles(BiCopiesarticlesId id, BiArticles biArticles, BiEtatarticle biEtatarticle, Set<BiEmprunts> biEmpruntses) {
       this.id = id;
       this.biArticles = biArticles;
       this.biEtatarticle = biEtatarticle;
       this.biEmpruntses = biEmpruntses;
    }
   
    public BiCopiesarticlesId getId() {
        return this.id;
    }
    
    public void setId(BiCopiesarticlesId id) {
        this.id = id;
    }
    public BiArticles getBiArticles() {
        return this.biArticles;
    }
    
    public void setBiArticles(BiArticles biArticles) {
        this.biArticles = biArticles;
    }
    public BiEtatarticle getBiEtatarticle() {
        return this.biEtatarticle;
    }
    
    public void setBiEtatarticle(BiEtatarticle biEtatarticle) {
        this.biEtatarticle = biEtatarticle;
    }
    public Set<BiEmprunts> getBiEmpruntses() {
        return this.biEmpruntses;
    }
    
    public void setBiEmpruntses(Set<BiEmprunts> biEmpruntses) {
        this.biEmpruntses = biEmpruntses;
    }




}


