package com.bouchardm.tp3.biblio.mapping;
// Generated 2013-12-14 16:42:46 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * BiCopiesarticles generated by hbm2java
 */
public class BiCopiesarticles  implements java.io.Serializable {


     private BiCopiesarticlesId id;
     private BiArticles biArticles;
     private char indicateurDisponible;
     private Set<BiEmprunts> biEmpruntses = new HashSet<BiEmprunts>(0);

    public BiCopiesarticles() {
    }

	
    public BiCopiesarticles(BiCopiesarticlesId id, BiArticles biArticles, char indicateurDisponible) {
        this.id = id;
        this.biArticles = biArticles;
        this.indicateurDisponible = indicateurDisponible;
    }
    public BiCopiesarticles(BiCopiesarticlesId id, BiArticles biArticles, char indicateurDisponible, Set<BiEmprunts> biEmpruntses) {
       this.id = id;
       this.biArticles = biArticles;
       this.indicateurDisponible = indicateurDisponible;
       this.biEmpruntses = biEmpruntses;
    }
   
    public BiCopiesarticlesId getId() {
        return this.id;
    }
    
    public void setId(BiCopiesarticlesId id) {
        this.id = id;
    }
    public BiArticles getBiArticles() {
        return this.biArticles;
    }
    
    public void setBiArticles(BiArticles biArticles) {
        this.biArticles = biArticles;
    }
    public char getIndicateurDisponible() {
        return this.indicateurDisponible;
    }
    
    public void setIndicateurDisponible(char indicateurDisponible) {
        this.indicateurDisponible = indicateurDisponible;
    }
    public Set<BiEmprunts> getBiEmpruntses() {
        return this.biEmpruntses;
    }
    
    public void setBiEmpruntses(Set<BiEmprunts> biEmpruntses) {
        this.biEmpruntses = biEmpruntses;
    }




}


