package com.bouchardm.tp3.biblio.mapping;
// Generated 2013-12-14 16:42:46 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * BiCommentaires generated by hbm2java
 */
public class BiCommentaires  implements java.io.Serializable {


     private int commentaireId;
     private BiEmprunts biEmprunts;
     private String commentaire;
     private Date datetimeCommentaire;

    public BiCommentaires() {
    }

    public BiCommentaires(int commentaireId, BiEmprunts biEmprunts, String commentaire, Date datetimeCommentaire) {
       this.commentaireId = commentaireId;
       this.biEmprunts = biEmprunts;
       this.commentaire = commentaire;
       this.datetimeCommentaire = datetimeCommentaire;
    }
   
    public int getCommentaireId() {
        return this.commentaireId;
    }
    
    public void setCommentaireId(int commentaireId) {
        this.commentaireId = commentaireId;
    }
    public BiEmprunts getBiEmprunts() {
        return this.biEmprunts;
    }
    
    public void setBiEmprunts(BiEmprunts biEmprunts) {
        this.biEmprunts = biEmprunts;
    }
    public String getCommentaire() {
        return this.commentaire;
    }
    
    public void setCommentaire(String commentaire) {
        this.commentaire = commentaire;
    }
    public Date getDatetimeCommentaire() {
        return this.datetimeCommentaire;
    }
    
    public void setDatetimeCommentaire(Date datetimeCommentaire) {
        this.datetimeCommentaire = datetimeCommentaire;
    }




}


