package com.bouchardm.tp3.biblio.mapping;
// Generated 2013-12-16 12:24:15 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * BiEtatarticle generated by hbm2java
 */
public class BiEtatarticle  implements java.io.Serializable {


     private Integer id;
     private String valeur;
     private Set<BiCopiesarticles> biCopiesarticleses = new HashSet<BiCopiesarticles>(0);

    public BiEtatarticle() {
    }

	
    public BiEtatarticle(String valeur) {
        this.valeur = valeur;
    }
    public BiEtatarticle(String valeur, Set<BiCopiesarticles> biCopiesarticleses) {
       this.valeur = valeur;
       this.biCopiesarticleses = biCopiesarticleses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getValeur() {
        return this.valeur;
    }
    
    public void setValeur(String valeur) {
        this.valeur = valeur;
    }
    public Set<BiCopiesarticles> getBiCopiesarticleses() {
        return this.biCopiesarticleses;
    }
    
    public void setBiCopiesarticleses(Set<BiCopiesarticles> biCopiesarticleses) {
        this.biCopiesarticleses = biCopiesarticleses;
    }




}


