package com.bouchardm.tp3.biblio.mapping;
// Generated 2013-12-16 12:24:15 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * BiModespaiements generated by hbm2java
 */
public class BiModespaiements  implements java.io.Serializable {


     private String modePaiementCd;
     private String cdDescFr;
     private String cdDescEn;
     private Set<BiEmprunts> biEmpruntses = new HashSet<BiEmprunts>(0);

    public BiModespaiements() {
    }

	
    public BiModespaiements(String modePaiementCd, String cdDescFr, String cdDescEn) {
        this.modePaiementCd = modePaiementCd;
        this.cdDescFr = cdDescFr;
        this.cdDescEn = cdDescEn;
    }
    public BiModespaiements(String modePaiementCd, String cdDescFr, String cdDescEn, Set<BiEmprunts> biEmpruntses) {
       this.modePaiementCd = modePaiementCd;
       this.cdDescFr = cdDescFr;
       this.cdDescEn = cdDescEn;
       this.biEmpruntses = biEmpruntses;
    }
   
    public String getModePaiementCd() {
        return this.modePaiementCd;
    }
    
    public void setModePaiementCd(String modePaiementCd) {
        this.modePaiementCd = modePaiementCd;
    }
    public String getCdDescFr() {
        return this.cdDescFr;
    }
    
    public void setCdDescFr(String cdDescFr) {
        this.cdDescFr = cdDescFr;
    }
    public String getCdDescEn() {
        return this.cdDescEn;
    }
    
    public void setCdDescEn(String cdDescEn) {
        this.cdDescEn = cdDescEn;
    }
    public Set<BiEmprunts> getBiEmpruntses() {
        return this.biEmpruntses;
    }
    
    public void setBiEmpruntses(Set<BiEmprunts> biEmpruntses) {
        this.biEmpruntses = biEmpruntses;
    }




}


