package com.bouchardm.tp3.biblio.mapping;
// Generated 2013-12-14 16:42:46 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * BiProvinces generated by hbm2java
 */
public class BiProvinces  implements java.io.Serializable {


     private String provCode;
     private String provDescFr;
     private String provDescEn;
     private BigDecimal pcTaxeProv;
     private BigDecimal pcTaxeFed;
     private Set<BiMembres> biMembreses = new HashSet<BiMembres>(0);
     private Set<BiMaisonseditions> biMaisonseditionses = new HashSet<BiMaisonseditions>(0);

    public BiProvinces() {
    }

	
    public BiProvinces(String provCode, String provDescFr, String provDescEn, BigDecimal pcTaxeProv, BigDecimal pcTaxeFed) {
        this.provCode = provCode;
        this.provDescFr = provDescFr;
        this.provDescEn = provDescEn;
        this.pcTaxeProv = pcTaxeProv;
        this.pcTaxeFed = pcTaxeFed;
    }
    public BiProvinces(String provCode, String provDescFr, String provDescEn, BigDecimal pcTaxeProv, BigDecimal pcTaxeFed, Set<BiMembres> biMembreses, Set<BiMaisonseditions> biMaisonseditionses) {
       this.provCode = provCode;
       this.provDescFr = provDescFr;
       this.provDescEn = provDescEn;
       this.pcTaxeProv = pcTaxeProv;
       this.pcTaxeFed = pcTaxeFed;
       this.biMembreses = biMembreses;
       this.biMaisonseditionses = biMaisonseditionses;
    }
   
    public String getProvCode() {
        return this.provCode;
    }
    
    public void setProvCode(String provCode) {
        this.provCode = provCode;
    }
    public String getProvDescFr() {
        return this.provDescFr;
    }
    
    public void setProvDescFr(String provDescFr) {
        this.provDescFr = provDescFr;
    }
    public String getProvDescEn() {
        return this.provDescEn;
    }
    
    public void setProvDescEn(String provDescEn) {
        this.provDescEn = provDescEn;
    }
    public BigDecimal getPcTaxeProv() {
        return this.pcTaxeProv;
    }
    
    public void setPcTaxeProv(BigDecimal pcTaxeProv) {
        this.pcTaxeProv = pcTaxeProv;
    }
    public BigDecimal getPcTaxeFed() {
        return this.pcTaxeFed;
    }
    
    public void setPcTaxeFed(BigDecimal pcTaxeFed) {
        this.pcTaxeFed = pcTaxeFed;
    }
    public Set<BiMembres> getBiMembreses() {
        return this.biMembreses;
    }
    
    public void setBiMembreses(Set<BiMembres> biMembreses) {
        this.biMembreses = biMembreses;
    }
    public Set<BiMaisonseditions> getBiMaisonseditionses() {
        return this.biMaisonseditionses;
    }
    
    public void setBiMaisonseditionses(Set<BiMaisonseditions> biMaisonseditionses) {
        this.biMaisonseditionses = biMaisonseditionses;
    }




}


