package com.bouchardm.tp3.biblio.mapping;
// Generated 2013-12-14 16:42:46 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * BiReservationsId generated by hbm2java
 */
public class BiReservationsId  implements java.io.Serializable {


     private int idMembre;
     private String idArticle;
     private Date dateReservation;

    public BiReservationsId() {
    }

    public BiReservationsId(int idMembre, String idArticle, Date dateReservation) {
       this.idMembre = idMembre;
       this.idArticle = idArticle;
       this.dateReservation = dateReservation;
    }
   
    public int getIdMembre() {
        return this.idMembre;
    }
    
    public void setIdMembre(int idMembre) {
        this.idMembre = idMembre;
    }
    public String getIdArticle() {
        return this.idArticle;
    }
    
    public void setIdArticle(String idArticle) {
        this.idArticle = idArticle;
    }
    public Date getDateReservation() {
        return this.dateReservation;
    }
    
    public void setDateReservation(Date dateReservation) {
        this.dateReservation = dateReservation;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BiReservationsId) ) return false;
		 BiReservationsId castOther = ( BiReservationsId ) other; 
         
		 return (this.getIdMembre()==castOther.getIdMembre())
 && ( (this.getIdArticle()==castOther.getIdArticle()) || ( this.getIdArticle()!=null && castOther.getIdArticle()!=null && this.getIdArticle().equals(castOther.getIdArticle()) ) )
 && ( (this.getDateReservation()==castOther.getDateReservation()) || ( this.getDateReservation()!=null && castOther.getDateReservation()!=null && this.getDateReservation().equals(castOther.getDateReservation()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdMembre();
         result = 37 * result + ( getIdArticle() == null ? 0 : this.getIdArticle().hashCode() );
         result = 37 * result + ( getDateReservation() == null ? 0 : this.getDateReservation().hashCode() );
         return result;
   }   


}


