package com.bouchardm.tp3.biblio.mapping;
// Generated 2013-12-16 12:24:15 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * BiTypesmembres generated by hbm2java
 */
public class BiTypesmembres  implements java.io.Serializable {


     private char typeMembre;
     private String typeDescFr;
     private String typeDescEn;
     private byte nbJoursSurEmprunt;
     private Set<BiMembres> biMembreses = new HashSet<BiMembres>(0);

    public BiTypesmembres() {
    }

	
    public BiTypesmembres(char typeMembre, String typeDescFr, String typeDescEn, byte nbJoursSurEmprunt) {
        this.typeMembre = typeMembre;
        this.typeDescFr = typeDescFr;
        this.typeDescEn = typeDescEn;
        this.nbJoursSurEmprunt = nbJoursSurEmprunt;
    }
    public BiTypesmembres(char typeMembre, String typeDescFr, String typeDescEn, byte nbJoursSurEmprunt, Set<BiMembres> biMembreses) {
       this.typeMembre = typeMembre;
       this.typeDescFr = typeDescFr;
       this.typeDescEn = typeDescEn;
       this.nbJoursSurEmprunt = nbJoursSurEmprunt;
       this.biMembreses = biMembreses;
    }
   
    public char getTypeMembre() {
        return this.typeMembre;
    }
    
    public void setTypeMembre(char typeMembre) {
        this.typeMembre = typeMembre;
    }
    public String getTypeDescFr() {
        return this.typeDescFr;
    }
    
    public void setTypeDescFr(String typeDescFr) {
        this.typeDescFr = typeDescFr;
    }
    public String getTypeDescEn() {
        return this.typeDescEn;
    }
    
    public void setTypeDescEn(String typeDescEn) {
        this.typeDescEn = typeDescEn;
    }
    public byte getNbJoursSurEmprunt() {
        return this.nbJoursSurEmprunt;
    }
    
    public void setNbJoursSurEmprunt(byte nbJoursSurEmprunt) {
        this.nbJoursSurEmprunt = nbJoursSurEmprunt;
    }
    public Set<BiMembres> getBiMembreses() {
        return this.biMembreses;
    }
    
    public void setBiMembreses(Set<BiMembres> biMembreses) {
        this.biMembreses = biMembreses;
    }




}


