package com.bouchardm.tp3.biblio.mapping;
// Generated 2013-12-14 16:42:46 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * BiTypearticles generated by hbm2java
 */
public class BiTypearticles  implements java.io.Serializable {


     private String typeArticle;
     private String typeArticleDescFr;
     private String typeArticleDescEn;
     private BigDecimal amendeParJour;
     private Set<BiArticles> biArticleses = new HashSet<BiArticles>(0);

    public BiTypearticles() {
    }

	
    public BiTypearticles(String typeArticle, String typeArticleDescFr, String typeArticleDescEn, BigDecimal amendeParJour) {
        this.typeArticle = typeArticle;
        this.typeArticleDescFr = typeArticleDescFr;
        this.typeArticleDescEn = typeArticleDescEn;
        this.amendeParJour = amendeParJour;
    }
    public BiTypearticles(String typeArticle, String typeArticleDescFr, String typeArticleDescEn, BigDecimal amendeParJour, Set<BiArticles> biArticleses) {
       this.typeArticle = typeArticle;
       this.typeArticleDescFr = typeArticleDescFr;
       this.typeArticleDescEn = typeArticleDescEn;
       this.amendeParJour = amendeParJour;
       this.biArticleses = biArticleses;
    }
   
    public String getTypeArticle() {
        return this.typeArticle;
    }
    
    public void setTypeArticle(String typeArticle) {
        this.typeArticle = typeArticle;
    }
    public String getTypeArticleDescFr() {
        return this.typeArticleDescFr;
    }
    
    public void setTypeArticleDescFr(String typeArticleDescFr) {
        this.typeArticleDescFr = typeArticleDescFr;
    }
    public String getTypeArticleDescEn() {
        return this.typeArticleDescEn;
    }
    
    public void setTypeArticleDescEn(String typeArticleDescEn) {
        this.typeArticleDescEn = typeArticleDescEn;
    }
    public BigDecimal getAmendeParJour() {
        return this.amendeParJour;
    }
    
    public void setAmendeParJour(BigDecimal amendeParJour) {
        this.amendeParJour = amendeParJour;
    }
    public Set<BiArticles> getBiArticleses() {
        return this.biArticleses;
    }
    
    public void setBiArticleses(Set<BiArticles> biArticleses) {
        this.biArticleses = biArticleses;
    }




}


